version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    platform: linux/amd64
    command: bin/long_polling
    volumes:
      - ./:/home/project
      - backend-modules:/usr/local/bundle
    env_file: .env
    links:
      - postgresql

  postgresql:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    platform: linux/amd64
    volumes:
      - postgres-data:/data
    env_file: .env

volumes:
  backend-modules:
  postgres-data:
