version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    platform: linux/amd64
    command: bin/long_polling
    volumes:
      - ./:/home/project
      - backend-modules:/usr/local/bundle
    env_file: .env

volumes:
  backend-modules:
